//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.08 at 03:12:48 PM IST 
//


package com.ing.app.model.xml.srumutil;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.ing.app.model.xml.srumutil package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ing.app.model.xml.srumutil
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordSetRows }
     */
    public RecordSetRows createRecordSetRows() {
        return new RecordSetRows();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record }
     */
    public RecordSetRows.Record createRecordSetRowsRecord() {
        return new RecordSetRows.Record();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.EnergyLoss }
     */
    public RecordSetRows.Record.EnergyLoss createRecordSetRowsRecordEnergyLoss() {
        return new RecordSetRows.Record.EnergyLoss();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.CPUEnergyConsumption }
     */
    public RecordSetRows.Record.CPUEnergyConsumption createRecordSetRowsRecordCPUEnergyConsumption() {
        return new RecordSetRows.Record.CPUEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.SocEnergyConsumption }
     */
    public RecordSetRows.Record.SocEnergyConsumption createRecordSetRowsRecordSocEnergyConsumption() {
        return new RecordSetRows.Record.SocEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.DisplayEnergyConsumption }
     */
    public RecordSetRows.Record.DisplayEnergyConsumption createRecordSetRowsRecordDisplayEnergyConsumption() {
        return new RecordSetRows.Record.DisplayEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.DiskEnergyConsumption }
     */
    public RecordSetRows.Record.DiskEnergyConsumption createRecordSetRowsRecordDiskEnergyConsumption() {
        return new RecordSetRows.Record.DiskEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.NetworkEnergyConsumption }
     */
    public RecordSetRows.Record.NetworkEnergyConsumption createRecordSetRowsRecordNetworkEnergyConsumption() {
        return new RecordSetRows.Record.NetworkEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.MBBEnergyConsumption }
     */
    public RecordSetRows.Record.MBBEnergyConsumption createRecordSetRowsRecordMBBEnergyConsumption() {
        return new RecordSetRows.Record.MBBEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.OtherEnergyConsumption }
     */
    public RecordSetRows.Record.OtherEnergyConsumption createRecordSetRowsRecordOtherEnergyConsumption() {
        return new RecordSetRows.Record.OtherEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.EmiEnergyConsumption }
     */
    public RecordSetRows.Record.EmiEnergyConsumption createRecordSetRowsRecordEmiEnergyConsumption() {
        return new RecordSetRows.Record.EmiEnergyConsumption();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.CPUEnergyConsumptionWorkOnBehalf }
     */
    public RecordSetRows.Record.CPUEnergyConsumptionWorkOnBehalf createRecordSetRowsRecordCPUEnergyConsumptionWorkOnBehalf() {
        return new RecordSetRows.Record.CPUEnergyConsumptionWorkOnBehalf();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.CPUEnergyConsumptionAttributed }
     */
    public RecordSetRows.Record.CPUEnergyConsumptionAttributed createRecordSetRowsRecordCPUEnergyConsumptionAttributed() {
        return new RecordSetRows.Record.CPUEnergyConsumptionAttributed();
    }

    /**
     * Create an instance of {@link RecordSetRows.Record.TotalEnergyConsumption }
     */
    public RecordSetRows.Record.TotalEnergyConsumption createRecordSetRowsRecordTotalEnergyConsumption() {
        return new RecordSetRows.Record.TotalEnergyConsumption();
    }

}
