//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.08 at 03:12:48 PM IST 
//


package com.ing.app.model.xml.srumutil;

import jakarta.xml.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Record" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EnergyLoss"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="CPUEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SocEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DisplayEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="DiskEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="NetworkEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="MBBEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="OtherEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="EmiEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="CPUEnergyConsumptionWorkOnBehalf"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="CPUEnergyConsumptionAttributed"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="TotalEnergyConsumption"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="AppId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="UserId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="OnBattery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="ScreenOn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="BatterySaverActive" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="LowPowerEpochActive" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Foreground" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="InteractivityState" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Container" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Committed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="TimeInMSec" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
 *                 &lt;attribute name="MeasuredBitmap" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "record"
})
@XmlRootElement(name = "RecordSetRows")
public class RecordSetRows {

    @XmlElement(name = "Record", required = true)
    protected List<Record> record;

    /**
     * Gets the value of the record property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the record property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecord().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Record }
     */
    public List<Record> getRecord() {
        if (record == null) {
            record = new ArrayList<Record>();
        }
        return this.record;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EnergyLoss"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CPUEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SocEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DisplayEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="DiskEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="NetworkEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="MBBEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="OtherEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="EmiEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CPUEnergyConsumptionWorkOnBehalf"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CPUEnergyConsumptionAttributed"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="TotalEnergyConsumption"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="AppId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="UserId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="OnBattery" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="ScreenOn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="BatterySaverActive" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="LowPowerEpochActive" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Foreground" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="InteractivityState" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Container" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="Committed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="TimeInMSec" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
     *       &lt;attribute name="MeasuredBitmap" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "energyLoss",
            "cpuEnergyConsumption",
            "socEnergyConsumption",
            "displayEnergyConsumption",
            "diskEnergyConsumption",
            "networkEnergyConsumption",
            "mbbEnergyConsumption",
            "otherEnergyConsumption",
            "emiEnergyConsumption",
            "cpuEnergyConsumptionWorkOnBehalf",
            "cpuEnergyConsumptionAttributed",
            "totalEnergyConsumption"
    })
    public static class Record {

        @XmlElement(name = "EnergyLoss", required = true)
        protected EnergyLoss energyLoss;
        @XmlElement(name = "CPUEnergyConsumption", required = true)
        protected CPUEnergyConsumption cpuEnergyConsumption;
        @XmlElement(name = "SocEnergyConsumption", required = true)
        protected SocEnergyConsumption socEnergyConsumption;
        @XmlElement(name = "DisplayEnergyConsumption", required = true)
        protected DisplayEnergyConsumption displayEnergyConsumption;
        @XmlElement(name = "DiskEnergyConsumption", required = true)
        protected DiskEnergyConsumption diskEnergyConsumption;
        @XmlElement(name = "NetworkEnergyConsumption", required = true)
        protected NetworkEnergyConsumption networkEnergyConsumption;
        @XmlElement(name = "MBBEnergyConsumption", required = true)
        protected MBBEnergyConsumption mbbEnergyConsumption;
        @XmlElement(name = "OtherEnergyConsumption", required = true)
        protected OtherEnergyConsumption otherEnergyConsumption;
        @XmlElement(name = "EmiEnergyConsumption", required = true)
        protected EmiEnergyConsumption emiEnergyConsumption;
        @XmlElement(name = "CPUEnergyConsumptionWorkOnBehalf", required = true)
        protected CPUEnergyConsumptionWorkOnBehalf cpuEnergyConsumptionWorkOnBehalf;
        @XmlElement(name = "CPUEnergyConsumptionAttributed", required = true)
        protected CPUEnergyConsumptionAttributed cpuEnergyConsumptionAttributed;
        @XmlElement(name = "TotalEnergyConsumption", required = true)
        protected TotalEnergyConsumption totalEnergyConsumption;
        @XmlAttribute(name = "AppId", required = true)
        protected String appId;
        @XmlAttribute(name = "UserId", required = true)
        protected String userId;
        @XmlAttribute(name = "TimeStamp", required = true)
        protected String timeStamp;
        @XmlAttribute(name = "OnBattery", required = true)
        protected String onBattery;
        @XmlAttribute(name = "ScreenOn", required = true)
        protected String screenOn;
        @XmlAttribute(name = "BatterySaverActive", required = true)
        protected String batterySaverActive;
        @XmlAttribute(name = "LowPowerEpochActive", required = true)
        protected String lowPowerEpochActive;
        @XmlAttribute(name = "Foreground", required = true)
        protected String foreground;
        @XmlAttribute(name = "InteractivityState", required = true)
        protected String interactivityState;
        @XmlAttribute(name = "Container", required = true)
        protected String container;
        @XmlAttribute(name = "Committed", required = true)
        protected String committed;
        @XmlAttribute(name = "TimeInMSec", required = true)
        @XmlSchemaType(name = "unsignedShort")
        protected int timeInMSec;
        @XmlAttribute(name = "MeasuredBitmap", required = true)
        protected String measuredBitmap;

        /**
         * Gets the value of the energyLoss property.
         *
         * @return possible object is
         * {@link EnergyLoss }
         */
        public EnergyLoss getEnergyLoss() {
            return energyLoss;
        }

        /**
         * Sets the value of the energyLoss property.
         *
         * @param value allowed object is
         *              {@link EnergyLoss }
         */
        public void setEnergyLoss(EnergyLoss value) {
            this.energyLoss = value;
        }

        /**
         * Gets the value of the cpuEnergyConsumption property.
         *
         * @return possible object is
         * {@link CPUEnergyConsumption }
         */
        public CPUEnergyConsumption getCPUEnergyConsumption() {
            return cpuEnergyConsumption;
        }

        /**
         * Sets the value of the cpuEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link CPUEnergyConsumption }
         */
        public void setCPUEnergyConsumption(CPUEnergyConsumption value) {
            this.cpuEnergyConsumption = value;
        }

        /**
         * Gets the value of the socEnergyConsumption property.
         *
         * @return possible object is
         * {@link SocEnergyConsumption }
         */
        public SocEnergyConsumption getSocEnergyConsumption() {
            return socEnergyConsumption;
        }

        /**
         * Sets the value of the socEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link SocEnergyConsumption }
         */
        public void setSocEnergyConsumption(SocEnergyConsumption value) {
            this.socEnergyConsumption = value;
        }

        /**
         * Gets the value of the displayEnergyConsumption property.
         *
         * @return possible object is
         * {@link DisplayEnergyConsumption }
         */
        public DisplayEnergyConsumption getDisplayEnergyConsumption() {
            return displayEnergyConsumption;
        }

        /**
         * Sets the value of the displayEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link DisplayEnergyConsumption }
         */
        public void setDisplayEnergyConsumption(DisplayEnergyConsumption value) {
            this.displayEnergyConsumption = value;
        }

        /**
         * Gets the value of the diskEnergyConsumption property.
         *
         * @return possible object is
         * {@link DiskEnergyConsumption }
         */
        public DiskEnergyConsumption getDiskEnergyConsumption() {
            return diskEnergyConsumption;
        }

        /**
         * Sets the value of the diskEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link DiskEnergyConsumption }
         */
        public void setDiskEnergyConsumption(DiskEnergyConsumption value) {
            this.diskEnergyConsumption = value;
        }

        /**
         * Gets the value of the networkEnergyConsumption property.
         *
         * @return possible object is
         * {@link NetworkEnergyConsumption }
         */
        public NetworkEnergyConsumption getNetworkEnergyConsumption() {
            return networkEnergyConsumption;
        }

        /**
         * Sets the value of the networkEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link NetworkEnergyConsumption }
         */
        public void setNetworkEnergyConsumption(NetworkEnergyConsumption value) {
            this.networkEnergyConsumption = value;
        }

        /**
         * Gets the value of the mbbEnergyConsumption property.
         *
         * @return possible object is
         * {@link MBBEnergyConsumption }
         */
        public MBBEnergyConsumption getMBBEnergyConsumption() {
            return mbbEnergyConsumption;
        }

        /**
         * Sets the value of the mbbEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link MBBEnergyConsumption }
         */
        public void setMBBEnergyConsumption(MBBEnergyConsumption value) {
            this.mbbEnergyConsumption = value;
        }

        /**
         * Gets the value of the otherEnergyConsumption property.
         *
         * @return possible object is
         * {@link OtherEnergyConsumption }
         */
        public OtherEnergyConsumption getOtherEnergyConsumption() {
            return otherEnergyConsumption;
        }

        /**
         * Sets the value of the otherEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link OtherEnergyConsumption }
         */
        public void setOtherEnergyConsumption(OtherEnergyConsumption value) {
            this.otherEnergyConsumption = value;
        }

        /**
         * Gets the value of the emiEnergyConsumption property.
         *
         * @return possible object is
         * {@link EmiEnergyConsumption }
         */
        public EmiEnergyConsumption getEmiEnergyConsumption() {
            return emiEnergyConsumption;
        }

        /**
         * Sets the value of the emiEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link EmiEnergyConsumption }
         */
        public void setEmiEnergyConsumption(EmiEnergyConsumption value) {
            this.emiEnergyConsumption = value;
        }

        /**
         * Gets the value of the cpuEnergyConsumptionWorkOnBehalf property.
         *
         * @return possible object is
         * {@link CPUEnergyConsumptionWorkOnBehalf }
         */
        public CPUEnergyConsumptionWorkOnBehalf getCPUEnergyConsumptionWorkOnBehalf() {
            return cpuEnergyConsumptionWorkOnBehalf;
        }

        /**
         * Sets the value of the cpuEnergyConsumptionWorkOnBehalf property.
         *
         * @param value allowed object is
         *              {@link CPUEnergyConsumptionWorkOnBehalf }
         */
        public void setCPUEnergyConsumptionWorkOnBehalf(CPUEnergyConsumptionWorkOnBehalf value) {
            this.cpuEnergyConsumptionWorkOnBehalf = value;
        }

        /**
         * Gets the value of the cpuEnergyConsumptionAttributed property.
         *
         * @return possible object is
         * {@link CPUEnergyConsumptionAttributed }
         */
        public CPUEnergyConsumptionAttributed getCPUEnergyConsumptionAttributed() {
            return cpuEnergyConsumptionAttributed;
        }

        /**
         * Sets the value of the cpuEnergyConsumptionAttributed property.
         *
         * @param value allowed object is
         *              {@link CPUEnergyConsumptionAttributed }
         */
        public void setCPUEnergyConsumptionAttributed(CPUEnergyConsumptionAttributed value) {
            this.cpuEnergyConsumptionAttributed = value;
        }

        /**
         * Gets the value of the totalEnergyConsumption property.
         *
         * @return possible object is
         * {@link TotalEnergyConsumption }
         */
        public TotalEnergyConsumption getTotalEnergyConsumption() {
            return totalEnergyConsumption;
        }

        /**
         * Sets the value of the totalEnergyConsumption property.
         *
         * @param value allowed object is
         *              {@link TotalEnergyConsumption }
         */
        public void setTotalEnergyConsumption(TotalEnergyConsumption value) {
            this.totalEnergyConsumption = value;
        }

        /**
         * Gets the value of the appId property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getAppId() {
            return appId;
        }

        /**
         * Sets the value of the appId property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setAppId(String value) {
            this.appId = value;
        }

        /**
         * Gets the value of the userId property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setUserId(String value) {
            this.userId = value;
        }

        /**
         * Gets the value of the timeStamp property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getTimeStamp() {
            return timeStamp;
        }

        /**
         * Sets the value of the timeStamp property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setTimeStamp(String value) {
            this.timeStamp = value;
        }

        /**
         * Gets the value of the onBattery property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getOnBattery() {
            return onBattery;
        }

        /**
         * Sets the value of the onBattery property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setOnBattery(String value) {
            this.onBattery = value;
        }

        /**
         * Gets the value of the screenOn property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getScreenOn() {
            return screenOn;
        }

        /**
         * Sets the value of the screenOn property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setScreenOn(String value) {
            this.screenOn = value;
        }

        /**
         * Gets the value of the batterySaverActive property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getBatterySaverActive() {
            return batterySaverActive;
        }

        /**
         * Sets the value of the batterySaverActive property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setBatterySaverActive(String value) {
            this.batterySaverActive = value;
        }

        /**
         * Gets the value of the lowPowerEpochActive property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLowPowerEpochActive() {
            return lowPowerEpochActive;
        }

        /**
         * Sets the value of the lowPowerEpochActive property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLowPowerEpochActive(String value) {
            this.lowPowerEpochActive = value;
        }

        /**
         * Gets the value of the foreground property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getForeground() {
            return foreground;
        }

        /**
         * Sets the value of the foreground property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setForeground(String value) {
            this.foreground = value;
        }

        /**
         * Gets the value of the interactivityState property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getInteractivityState() {
            return interactivityState;
        }

        /**
         * Sets the value of the interactivityState property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setInteractivityState(String value) {
            this.interactivityState = value;
        }

        /**
         * Gets the value of the container property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getContainer() {
            return container;
        }

        /**
         * Sets the value of the container property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setContainer(String value) {
            this.container = value;
        }

        /**
         * Gets the value of the committed property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getCommitted() {
            return committed;
        }

        /**
         * Sets the value of the committed property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setCommitted(String value) {
            this.committed = value;
        }

        /**
         * Gets the value of the timeInMSec property.
         */
        public int getTimeInMSec() {
            return timeInMSec;
        }

        /**
         * Sets the value of the timeInMSec property.
         */
        public void setTimeInMSec(int value) {
            this.timeInMSec = value;
        }

        /**
         * Gets the value of the measuredBitmap property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMeasuredBitmap() {
            return measuredBitmap;
        }

        /**
         * Sets the value of the measuredBitmap property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMeasuredBitmap(String value) {
            this.measuredBitmap = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CPUEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected int value;

            /**
             * Gets the value of the value property.
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(int value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CPUEnergyConsumptionAttributed {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CPUEnergyConsumptionWorkOnBehalf {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DiskEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DisplayEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EmiEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EnergyLoss {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class MBBEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class NetworkEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected int value;

            /**
             * Gets the value of the value property.
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(int value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class OtherEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SocEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short value;

            /**
             * Gets the value of the value property.
             */
            public short getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(short value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="Value" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class TotalEnergyConsumption {

            @XmlAttribute(name = "Value", required = true)
            @XmlSchemaType(name = "unsignedShort")
            protected int value;

            /**
             * Gets the value of the value property.
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             */
            public void setValue(int value) {
                this.value = value;
            }

        }

    }

}
